config/routes.rb
Rails.application.routes.draw do

  match '/favorites', to: 'favorites#index', :via => 'get'
  post 'favorites/save' => 'favorites#save', :as => :save

  get 'people/show'

  get 'company/index'

  get 'home/index'

  root to: "home#index"
  devise_for :users, controllers: {
      sessions: 'users/sessions'
  }

end

app/models/company.rb
class Company < ActiveRecord::Base
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  validates :user, uniqueness: { scope: [:person, :company] }
end

app/models/person.rb
class Person < ActiveRecord::Base
  belongs_to :Company
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def after_sign_in_path_for(resource)
    company_index_path
  end
end

app/controllers/company_controller.rb
class CompanyController < ApplicationController
  before_action :authenticate_user!
  def index
    @companies = Company.all
  end
  def find_by_index(id)
    @company = Company.find(id)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!
  def index
    @user = current_user.id.to_s

    @favorites_companies = Favorite.where("\"user\" = ? AND \"company\" IS NOT NULL", @user).order(created_at: :desc)
    @favorites_people = Favorite.where("\"user\" = ? AND \"person\" IS NOT NULL", @user).order(created_at: :desc)

    @people_list = []

    @favorites_people.each do |fav_ppl|
      @temp = Person.find(fav_ppl.id)
      @name = fav_ppl.person + ', '
      @temp_comp = Company.find(@temp.company_id)
      @corp_name = @temp_comp.name+ ' company'
      @people_list.push([@name, @corp_name])
    end

    @count = @favorites_companies.length + @favorites_people.length

  end
  def save
    @user = current_user.id.to_s
    @favorite = Favorite.create(user: @user, company: params[:company_id], person: params[:person_id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :authenticate_user!
  def show
    @people_on_companies = Person.where("company_id = ?", params[:id])
    company = CompanyController.new
    @company = company.find_by_index(params[:id])
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/company_helper.rb
module CompanyHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/company/index.html.erb
<p> <%= button_to 'Favorites', favorites_path, :method => 'get' %> </p>
<h1>Here are companies that are in the system:</h1>
<% @companies.each do |company| %>
    <li><%=link_to( company.name + ', ' +  company.country, :controller => 'people',
      :action => 'show', :id => company.id)%></li>
    <p> <%= button_to "Favorite", save_path(:company_id => company.name), :remote => true%> <!/p>
    <br>
<%end %>
<p> <%= button_to 'Logout', destroy_user_session_path, :method => 'delete' %> </p>

app/views/favorites/index.html.erb
<h1>Here are favorited companies :</h1>
<h1>There are <%= @favorites_companies.length%> favorited companies</h1>
<% @favorites_companies.each do |favorite| %>
    <li class="company"><%=favorite.company.to_s + ', ' +  favorite.person.to_s%></li>
    <br>
<%end %>
<h1>Here are favorited people :</h1>
<h1>There are <%= @people_list.length%> favorited people</h1>
<% @people_list.each do |favorite| %>
    <li class="person"><%=favorite[0] + ' ' + favorite[1]%></li>
    <br>
<%end %>
<p> <%= button_to "Back", company_index_path, :method => 'get' %> </p>
<p> <%= button_to 'Logout', destroy_user_session_path, :method => 'delete' %> </p>

app/views/home/index.html.erb
<div class="container">
  <h1>Welcome!</h1>
  <p>Register to get started.</p>
  <p> <%= button_to 'Register', new_user_registration_path, :method => 'get' %> </p>
  <p> <%= button_to 'Login', new_user_session_path, :method => 'get' %> </p>
  <p> <%= button_to 'Logout', destroy_user_session_path, :method => 'delete' %> </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ARSv2</title>
  <%= stylesheet_link_tag 'default', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'default', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% content_for :top_content do %>
    <div class="jumbotron">
      <div class="container">
        <h1>Welcome!</h1>
        <p>Register to get started.</p>
        <p>
          <%= link_to 'Register', new_user_registration_path, class: 'btn btn-primary btn-lg' %>
        </p>
      </div>
    </div>
<% end %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/people/show.html.erb
<p> <%= button_to 'Favorites', favorites_path, :method => 'get' %> </p>
<h1>Here are People that are in the system for <%= @company.name %> stationed in <%= @company.country %> :</h1>
<% @people_on_companies.each do |person| %>
    <li><%= person.first_name + ', ' +  person.last_name%></li>
    <p> <%= button_to "Favorite", save_path(:person_id => person.first_name + ' ' + person.last_name), :remote => true %> </p>
<%end %>
<br>
<p> <%= button_to "Back", company_index_path, :method => 'get' %> </p>
<p> <%= button_to 'Logout', destroy_user_session_path, :method => 'delete' %> </p>